baseURL = "https://www.tapanshah.com/"
languageCode = "en-us"
title = "Tapan Shah - Homepage"
theme = "portfolio"

# Enable Google Analytics by entering your tracking code
#googleAnalytics = "UA-178221-5"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Welcome to my homepage"
  copyright = "&copy;2017 Tapan Shah"
  sidebarAbout = [
    "New York, NY."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Twitter Feed"
  url = "twitter/"
  

  [params.social]
  email         = "tapsboy at gmail dot com"
  twitter       = "https://twitter.com/tapsboy"
  googleplus    = "https://plus.google.com/+TapanShah1982"
  linkedin      = "https://www.linkedin.com/in/tapanshah/"
  stackoverflow = "https://stackoverflow.com/users/720644/tapsboy"
  instagram     = "https://www.instagram.com/tapsboy/"
  github        = "https://github.com/tapsboy"
  medium        = "https://medium.com/@tapsboy"
